### PR TITLE
Including Hardware Support for 6DoF Version of Kinova Gen3 

### PR DESCRIPTION
**Pull request by kwesiRutledge**
Thanks for making this repository, Vince!

This pull request should include two major additions to kinova_drake. Feel free to reject them if you see fit:
1. Adds support to the `KinovaStationHardwareInterface()` class for the 6DoF model. It does this by defining a new function `FindNumberOfRobotJoints()` which detects the number of joints on the robot. It does this inefficiently - by (i) opening a temporary connection to the base, (ii) then calling `GetMeasuredJointAngles()` from the Kinova API and finally (iii) closing the connection to the base. I didn't want to mess with the `__init__()` or `__enter__()` that you have and so I created this poor solution. Feel free to tweak it!
2. Includes the URDF and asscoiated OBJ files to visualize the 6DoF Kinova Gen3 with Drake. I didn't include a test or example for this, but I have [a test in a scratch-paper repo](https://github.com/kwesiRutledge/OzayGroupExploration/blob/main/drake/basictest4.py) that verifies this works. If you think it is necessary, then I can include it in this pull request.

Minor addition(s):
1. I added the .DS_Store suffix to the `.gitignore` file to ignore some temporary files that are created on Mac OS X.

Feel free to ask me any questions about the changes/future plans I have! (One is to add support to the simulation station for the 6DoF model.)

### CODE REVIEW

**Comment by vincekurtz** [comment]
Hi Kwesi, this looks great! I'd be happy to include these improvements. 

I do want to double check that it works reliably on our hardware before merging though - it might be early next week before I have a chance to do that. Supporting the 6DoF model in simulation sounds good too - and shouldn't be too hard.

**Comment by vincekurtz** [comment]
I do think it might be cleaner to have the number of degrees of freedom as a constructor argument (e.g., `n_dof=6`) rather than something that's detected automatically. Then such an argument could be used in both the simulation and hardware versions.

**Comment by kwesiRutledge** [comment]
That works. Should I close this pull request and then push a new branch that includes a constructor change instead?

**Comment by vincekurtz** [comment]
Yea, that's probably the easiest way to do it. And if you're opening a new pull request anyway it might be nice to separate the hardware part (contribution 1 per your post above) from the simulation urdf/obj part (contribution 2 above)

**Comment by kwesiRutledge** [comment]
Gotcha. Will do!

**Pull request closed without merging**
